sudo: required
services:
  - docker

before_install:
  - docker build -t irealsourav/cicdawsdemo -f Dockerfile.dev .

scripts:
  - docker run -e CI=true irealsourav/cicdawsdemo npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DockerWithTravisCICD"
  env: "Dockerwithtraviscicd-env"
  bucket_name: "elasticbeanstalk-us-east-2-688713631091"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master