sudo: required
services:
  - docker

before_install:
  - docker build -t irealsourav/cicdawsdemo -f Dockerfile.dev .

scripts:
  - docker run -e CI=true irealsourav/cicdawsdemo npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "CICDAWSDemo"
  env: "Cicdawsdemo-env"
  bucket_name: "elasticbeanstalk-us-east-2-688713631091"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"