sudo: required
services:
  - docker

before_install:
  - docker build -t irealsourav/cicdawsdemo -f Dockerfile.dev .

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DockerWithTravisCICD"
  env: "Dockerwithtraviscicd-env"
  bucket_name: "elasticbeanstalk-us-east-2-688713631091"
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY